version: "3.9"

services:
    users:
        image: ${DOCKER_IMAGE:-cralos062/lms-authnusers:latest}
        # container_name removido para permitir Blue e Green em simultâneo
        ports:
            - "${HOST_PORT:-8080}:8080"
        depends_on:
            postgres_users:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_users:5432/users_1
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_RABBITMQ_PORT: 5672
        networks:
            lms_network:
                aliases:
                    - users-service # O Readers continuará a usar este DNS
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.users-${COLOR:-blue}.rule=PathPrefix(`/api/users`)"
            - "traefik.http.services.users-${COLOR:-blue}.loadbalancer.server.port=8080"
        healthcheck:
            test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 40s
        deploy:
            update_config:
                order: start-first # Sobe o novo antes de desligar o antigo

    postgres_users:
        container_name: postgres_users
        image: postgres:18
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: users_1
        volumes:
            - postgres_users_volume:/var/lib/postgresql
        networks:
            - lms_network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s

networks:
    lms_network:
        external: true

volumes:
    postgres_users_volume: