version: "3.9"

services:
    users:
        image: ${DOCKER_IMAGE}
        container_name: users-${COLOR}
        ports:
            - "${HOST_PORT}:8080"
        depends_on:
            postgres_users:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_users:5432/users_1
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            FEATURE_MAINTENANCE_KILLSWITCH: ${KILLSWITCH_ACTIVE:-false}
            DARKLAUNCH_SECRET_HEADER: X-LMS-Beta-Access
        networks:
            lms_network:
                aliases:
                    - users-service
        labels:
            - "traefik.enable=true"
            # Router único por cor para evitar conflitos de nomes no Traefik
            - "traefik.http.routers.users-${COLOR}.rule=PathPrefix(`/api/users`)"
            - "traefik.http.routers.users-${COLOR}.entrypoints=web"
            # AMBOS os routers (Blue e Green) apontam para o MESMO serviço de Load Balancer
            - "traefik.http.routers.users-${COLOR}.service=users-canary-service"

            # Configuração de Pesos (Canary)
            - "traefik.http.services.users-canary-service.loadbalancer.weighted.services.users-${COLOR}-backend@docker"
            - "traefik.http.services.users-canary-service.loadbalancer.services.users-${COLOR}-backend@docker.weight=${WEIGHT:-0}"
            - "traefik.http.services.users-${COLOR}-backend@docker.loadbalancer.server.port=8080"

        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 40s

    postgres_users:
        image: postgres:18
        container_name: postgres-users-${COLOR}
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: users_1
        volumes:
            - postgres_users_volume_${COLOR}:/var/lib/postgresql
        networks:
            lms_network:
                aliases:
                    - postgres_users
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s

networks:
    lms_network:
        external: true

volumes:
    postgres_users_volume_blue:
    postgres_users_volume_green: