services:
    users:
        # Usamos a variável para o Jenkins injetar a tag correta
        image: ${DOCKER_IMAGE:-cralos062/lms-authnusers:latest}
        container_name: users-service
        ports:
            - "30081:8080" # Porta externa 30081 conforme planeado
        depends_on:
            postgres_users:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_users:5432/users_1
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_RABBITMQ_PORT: 5672
        networks:
            - lms_network

        # --- Requisito "Health checks in prod" ---
        healthcheck:
            # O Docker entra no container e tenta aceder ao endpoint interno
            test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
            interval: 20s        # Verifica a cada 20 segundos
            timeout: 10s         # Espera 10s pela resposta
            retries: 5           # Tenta 5 vezes antes de marcar como "unhealthy"
            start_period: 60 # Reduzi para o Jenkins não esperar tanto tempo

        # --- Requisito "Zero Downtime / Rolling Update" ---
        deploy:
            update_config:
                order: start-first
                failure_action: rollback

    postgres_users:
        container_name: postgres_users
        image: postgres:18
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: users_1
        volumes:
            - postgres_users_volume:/var/lib/postgresql  # montar diretamente em /var/lib/postgresql
        networks:
            - lms_network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            retries: 5
            timeout: 5s

networks:
    lms_network:
        external: true

volumes:
    postgres_users_volume: