version: "3.9"

services:
    users:
        image: ${DOCKER_IMAGE:-cralos062/lms-authnusers:latest}

        depends_on:
            postgres_users:
                condition: service_healthy

        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_users:5432/users_1
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            FEATURE_MAINTENANCE_KILLSWITCH: ${KILLSWITCH_ACTIVE:-false}
            DARKLAUNCH_SECRET_HEADER: X-LMS-Beta-Access

        networks:
            lms_network:
                aliases:
                    - users-service

        labels:
            - "traefik.enable=true"

            # Router único
            - "traefik.http.routers.users.rule=PathPrefix(`/api/users`)"

            # Service dinâmico (blue / green)
            - "traefik.http.routers.users.service=users-${COLOR}"
            - "traefik.http.services.users-${COLOR}.loadbalancer.server.port=8080"

        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 40s

    postgres_users:
        image: postgres:18
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: users_1
        volumes:
            - postgres_users_volume:/var/lib/postgresql
        networks:
            lms_network:
                aliases:
                    - postgres_users
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s

networks:
    lms_network:
        external: true

volumes:
    postgres_users_volume:
