version: "3.9"

services:
    readers:
        image: ${DOCKER_IMAGE}
        container_name: readers-${COLOR:-blue}
        ports:
            - "${HOST_PORT:-8090}:8090"
        depends_on:
            postgres_readers:
                condition: service_healthy
        environment:
            SPRING_PROFILES_ACTIVE: sql,bootstrap,base65,instance1
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_readers:5432/readers_1
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_RABBITMQ_PORT: 5672
        networks:
            lms_network:
                aliases:
                    - readers-service
        labels:
            - "traefik.enable=true"
            # Router único por cor
            - "traefik.http.routers.readers-${COLOR:-blue}.rule=PathPrefix(`/api/readers`)"
            - "traefik.http.routers.readers-${COLOR:-blue}.entrypoints=web"
            # Aponta para o serviço de balanceamento Canary
            - "traefik.http.routers.readers-${COLOR:-blue}.service=readers-canary-service"

            # Configuração de Pesos
            - "traefik.http.services.readers-canary-service.loadbalancer.weighted.services.readers-${COLOR:-blue}-backend@docker"
            - "traefik.http.services.readers-canary-service.loadbalancer.services.readers-${COLOR:-blue}-backend@docker.weight=${WEIGHT:-0}"
            - "traefik.http.services.readers-${COLOR:-blue}-backend@docker.loadbalancer.server.port=8090"

        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
            interval: 20s
            timeout: 10s
            retries: 5
            start_period: 60s

    postgres_readers:
        container_name: postgres-readers-${COLOR:-blue}
        image: postgres:18
        restart: always
        environment:
            POSTGRES_DB: readers_1
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_readers_volume_${COLOR:-blue}:/var/lib/postgresql
        networks:
            - lms_network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s

networks:
    lms_network:
        external: true

volumes:
    postgres_readers_volume_blue:
    postgres_readers_volume_green: