version: "3.9"

services:
    readers:
        image: ${DOCKER_IMAGE:-cralos062/lms-readers:latest}
        ports:
            - "${HOST_PORT:-8090}:8090"
        depends_on:
            postgres_readers:
                condition: service_healthy
        environment:
            SPRING_PROFILES_ACTIVE: sql,bootstrap,base65,instance1
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_readers:5432/readers_1
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            FEATURE_MAINTENANCE_KILLSWITCH: ${KILLSWITCH_ACTIVE:-false}
        networks:
            lms_network:
                aliases:
                    - readers-service
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.readers-${COLOR:-blue}-router.rule=PathPrefix(`/api/readers`)"
            - "traefik.http.routers.readers-${COLOR:-blue}-router.entrypoints=web"
            - "traefik.http.routers.readers-${COLOR:-blue}-router.service=readers-canary-service"

            # Load Balancer com Pesos
            - "traefik.http.services.readers-canary-service.loadbalancer.weighted.services.readers-${COLOR:-blue}-backend@docker"
            - "traefik.http.services.readers-canary-service.loadbalancer.services.readers-${COLOR:-blue}-backend@docker.weight=${WEIGHT:-0}"
            - "traefik.http.services.readers-${COLOR:-blue}-backend@docker.loadbalancer.server.port=8090"

        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 40s

    postgres_readers:
        image: postgres:18
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: readers_1
        volumes:
            - postgres_readers_volume_${COLOR:-blue}:/var/lib/postgresql/data
        networks:
            lms_network:
                aliases:
                    - postgres_readers
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s

networks:
    lms_network:
        external: true

volumes:
    postgres_readers_volume_blue:
    postgres_readers_volume_green: