version: "3.9"

services:
    readers:
        image: ${DOCKER_IMAGE}
        container_name: readers-${COLOR}
        ports:
            - "${HOST_PORT}:8090"
        depends_on:
            postgres_readers:
                condition: service_healthy
        environment:
            SPRING_PROFILES_ACTIVE: sql,bootstrap,base65,instance1
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_readers:5432/readers_1
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_RABBITMQ_PORT: 5672
        networks:
            lms_network:
                aliases:
                    - readers-service
        labels:
            - "traefik.enable=true"

            # 1. Roteamento: Router exclusivo para esta cor
            - "traefik.http.routers.readers-${COLOR}-router.rule=PathPrefix(`/api/readers`)"
            - "traefik.http.routers.readers-${COLOR}-router.entrypoints=web"

            # 2. Vinculação ao Serviço de Canary comum
            - "traefik.http.routers.readers-${COLOR}-router.service=readers-canary-service"

            # 3. Definição do Load Balancer Weighted (Canary)
            - "traefik.http.services.readers-canary-service.loadbalancer.weighted.services.readers-${COLOR}-backend@docker"
            - "traefik.http.services.readers-canary-service.loadbalancer.services.readers-${COLOR}-backend@docker.weight=${WEIGHT:-0}"

            # 4. Backend real deste container
            - "traefik.http.services.readers-${COLOR}-backend@docker.loadbalancer.server.port=8090"

        healthcheck:
            # O Traefik precisa que o status seja HEALTHY para ativar a rota
            test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
            interval: 20s
            timeout: 10s
            retries: 5
            start_period: 60s

    postgres_readers:
        container_name: postgres-readers-${COLOR}
        image: postgres:18
        restart: always
        environment:
            POSTGRES_DB: readers_1
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            # Correção no path interno do volume para garantir persistência
            - postgres_readers_volume_${COLOR}:/var/lib/postgresql/data
        networks:
            lms_network:
                aliases:
                    - postgres_readers
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s

networks:
    lms_network:
        external: true

volumes:
    postgres_readers_volume_blue:
    postgres_readers_volume_green: