version: "3.9"

services:
    readers:
        image: ${DOCKER_IMAGE:-cralos062/lms-readers:latest}
        # container_name removido para evitar conflitos no swap Blue/Green
        ports:
            - "${HOST_PORT:-8090}:8090"
        depends_on:
            postgres_readers:
                condition: service_healthy
        environment:
            SPRING_PROFILES_ACTIVE: sql,bootstrap,base65,instance1
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_readers:5432/readers_1
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            FEATURE_MAINTENANCE_KILLSWITCH: ${KILLSWITCH_ACTIVE:-false}
            DARKLAUNCH_SECRET_HEADER: X-LMS-Beta-Access
        networks:
            lms_network:
                aliases:
                    - readers-service
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.readers-${COLOR:-blue}.rule=PathPrefix(`/api/readers`)"
            - "traefik.http.services.readers-${COLOR:-blue}.loadbalancer.server.port=8090"
        healthcheck:
            # Usando wget para consistência com o teu exemplo do Users
            test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/actuator/health" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 40s
        deploy:
            update_config:
                order: start-first

    postgres_readers:
        image: postgres:18
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: readers_1
        volumes:
            # Volume partilhado ou específico por projeto conforme o prefixo -p
            - postgres_readers_volume:/var/lib/postgresql/data
        networks:
            lms_network:
                aliases:
                    - postgres_readers
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s

networks:
    lms_network:
        external: true

volumes:
    postgres_readers_volume: